Webpage template for SC21
IO500/webpage pull request #179
Opened 2021-09-14 16:22 UTC by JulianKunkel

2021-09-14 16:23 UTC, gmarkomanolis approved these changes

2021-09-14 18:11 UTC, adilger requested changes

2021-09-14 18:11 UTC, adilger commented on templates/Pages/bof_sc21.php
> +    $this->Breadcrumbs->add(__("ISC'21"), ['controller' => 'pages', 'action' => 'display', 'bof-isc21']);
Should be "SC'21" and 'bof-sc21'

2021-09-14 18:11 UTC, adilger commented on templates/Pages/bof_sc21.php
> +    <h2>ISC'21</h2>
Should be "SC'21"

2021-09-14 18:11 UTC, adilger commented on templates/Pages/bof_sc21.php
> +        since then for both ISC and SC. A BoF highlight is the presentation of the eighth IO500 list.
Should be "ninth", or just drop this and use "bi-annual IO500 list."

2021-09-14 19:38 UTC, adilger approved these changes

2021-09-21 20:54 UTC, gmarkomanolis approved these changes

2021-09-22 08:07 UTC, merged