Add files via upload
IO500/webpage pull request #191
Opened 2021-11-18 19:24 UTC by JulianKunkel

2021-11-27 06:53 UTC, jeanbez requested changes

2021-11-27 06:53 UTC, jeanbez commented on templates/Pages/bof_sc21.php
> +<p><a href="/webroot/files/SC21 IO500 Presentation.pdf">Slides</a></p>
To make the URL clean, could you please change the spaces to dash or underline?

2022-01-17 07:14 UTC, jeanbez commented on templates/Pages/bof_sc21.php
> +<p><a href="/webroot/files/SC21 IO500 Presentation.pdf">Slides</a></p>
@JulianKunkel are we including the slides?

2022-01-18 13:04 UTC, gmarkomanolis submitted a review, later dismissed

2022-05-11 06:26 UTC, gmarkomanolis approved these changes

2022-05-11 06:43 UTC, adilger approved these changes

2022-05-11 19:41 UTC, jeanbez approved these changes

2022-05-11 19:41 UTC, merged