Sc24 pages
IO500/webpage pull request #285
Opened 2024-09-11 22:12 UTC by seattleplus

2024-09-12 00:14 UTC, gflofst commented on templates/Pages/cfs_sc24.php
> +        The github repo has a new tag <code>io500-isc24</code> for the current
Shouldn't this be io500-sc24?

2024-09-12 00:14 UTC, gflofst reviewed
I think the one comment with the isc24 tag needs to be updated, but otherwise looks good.

2024-09-12 14:14 UTC, adilger requested changes
Lots of places need to replace "ISC" with "SC"

2024-09-12 14:14 UTC, adilger commented on templates/Pages/bof_sc24.php
> +    <h2>ISC'24</h2>
Should be SC'24

2024-09-12 14:14 UTC, adilger commented on templates/Pages/cfs_sc24.php
> +            [ 'controller' => 'pages', 'action' => 'display', 'bof-isc24' ],
Schools be bof-sc24

2024-09-12 14:14 UTC, adilger commented on templates/Pages/bof_sc24.php
> +    <!-- insert presentation link <a class="link" href="/files/ISC24_IO500_Presentation.pdf" target="_blank">BOF Slides</a> -->
Should be SC24

2024-09-12 14:14 UTC, adilger commented on templates/Pages/bof_sc24.php
> +        Official ISC event link: <a class="link" href="https://app.swapcard.com/widget/event/isc-high-performance-2024/planning/UGxhbm5pbmdfMTgyNjgxNQ==" target="_blank">IO500: The High-Performance S
This URL needs to be updated.

2024-09-12 14:14 UTC, adilger commented on templates/Pages/bof_sc24.php
> +                <td>Tuesday, May 14, 2024 10:05 AM to 11:05 aM</td>
Date needs to be updated.

2024-09-12 14:14 UTC, adilger commented on templates/Pages/bof_sc24.php
> +    $this->Breadcrumbs->add(__("ISC'24"), ['controller' => 'pages', 'action' => 'display', 'bof-isc24']);
Schools be SC'24 and bof-sc24.

2024-09-12 14:14 UTC, adilger commented on templates/Pages/bof_sc24.php
> +<?php $this->assign('title', 'Birds-of-a-Feather - ISC 24'); ?>
Shoukd be SC 24

2024-09-12 14:14 UTC, adilger commented on templates/Pages/cfs_sc24.php
> +        Stabilization Period: April 1st - April 15th, 2024
Dates need to be updated.

2024-09-12 14:14 UTC, adilger commented on templates/Pages/cfs_sc24.php
> +        for the upcoming 14th semi-annual IO500 Production and Research lists,
This is the 15th list, AFAICS.

2024-09-12 14:14 UTC, adilger commented on templates/Pages/cfs_sc24.php
> +        in conjunction with <strong>ISC'24</strong>.  Once again, we are also
SC'24

2024-09-12 14:14 UTC, adilger commented on templates/Pages/cfs_sc24.php
> +         ?>
Fix dates

2024-09-12 14:14 UTC, adilger commented on templates/Pages/cfs_sc24.php
> +        <?php echo $this->Html->link('ISC24 BoF',
SC24

2024-09-12 14:14 UTC, adilger commented on templates/Pages/cfs_sc24.php
> +            [ 'controller' => 'pages', 'action' => 'display', 'bof-isc24' ],
bof-sc24

2024-09-12 14:22 UTC, adilger requested changes
It was confusing that the first commit was only a copy of the ISC pages, and the later patches were doing the updates.

It would have been more clear if this was explained in the commit message. 

I _think_ the pages have been fixed, but I didn't see an update to the main BOF/Submissions pages to link to these new pages?

2024-09-13 00:42 UTC, seattleplus commented on templates/Pages/cfs_sc24.php
> +        The github repo has a new tag <code>io500-isc24</code> for the current
yes, udpating

2024-09-13 00:46 UTC, seattleplus commented
I updated the bofs and news page (I don't see a place to link in the CFS) and fixed the typo. How does this look?

2024-09-13 14:54 UTC, adilger approved these changes
LGTM

2024-09-13 20:50 UTC, gmarkomanolis commented
Approve

2024-09-13 20:54 UTC, gmarkomanolis approved these changes

2024-09-13 20:54 UTC, merged