Include SC20 BoF page
IO500/webpage pull request #60
Opened 2020-11-11 18:33 UTC by jeanbez

Includes a new page for SC20 BoF based on previous pages. I already updated the date, time, and venue information with data from SC website.

2020-11-11 18:34 UTC, jeanbez commented
I've gone ahead and created the template for the page based on previous versions. We just need to include the new information Jay mentioned.

2020-11-11 18:36 UTC, gmarkomanolis submitted a review, later dismissed

2020-11-11 19:22 UTC, johnbent submitted a review, later dismissed

2020-11-12 16:38 UTC, adilger commented on templates/Pages/bof_sc20.php
> +        The IO500 is quickly becoming the de facto benchmarking standard for HPC storage. Developed two years ago, the IO500 has published five official lists so far. A BoF highlight is the presentat
There are six previous lists now.

2020-11-12 16:40 UTC, adilger requested changes
Need to update "six official lists so far".

2020-11-12 18:23 UTC, JulianKunkel commented
Need to wait until after the weekend. Seems that SC releases the infos over the weekend.
As any attendee shall register to SC (as Exhibitor, which is free) to get access, maybe we shall not expose any URL at all.

2020-11-12 23:12 UTC, gflofst submitted a review, later dismissed

2020-11-13 09:13 UTC, JulianKunkel submitted a review, later dismissed

2020-11-16 17:20 UTC, jeanbez commented on templates/Pages/bof_sc20.php
> +        The IO500 is quickly becoming the de facto benchmarking standard for HPC storage. Developed two years ago, the IO500 has published five official lists so far. A BoF highlight is the presentat
Solved!

2020-11-16 17:20 UTC, jeanbez commented
Updated to six previous lists as requested

2020-11-16 19:02 UTC, gmarkomanolis approved these changes

2020-11-16 19:40 UTC, gflofst approved these changes

2020-11-16 20:06 UTC, adilger approved these changes

2020-11-16 20:07 UTC, JulianKunkel approved these changes

2020-11-18 14:53 UTC, johnbent approved these changes

2020-11-18 14:53 UTC, merged